---
  - name: Install updates (CentOS)
    tags: always
    yum:
     update_only: yes
     update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates (Ubuntu)
    tags: always
    apt:
     upgrade: dist
     update_cache: yes
    when: ansible_distribution == "Ubuntu"

